language: python
python:
  - "2.7"
  - "3.4"

sudo: required

install:
    - "./scripts/boostrap --travis --skip-preamble"

# command to run tests
script:
  - py.test tests --doctest-modules --pep8 hypatia -v --cov-report term-missing --cov=hypatia

after_success:
  - coveralls
